#!/usr/bin/env bash
# Displays  a list of currently running processes
# Shows all processes, for all users , including those which mightnot have TTY
# Displays in a User-oriented format and shows process hierarchy

ps -auxf
